export const SKILL_KEYWORDS: Record<string, string[]> = {
  javascript: [
    "javascript",
    "js",
    "es6",
    "typescript",
    "node",
    "nodejs",
    "frontend",
    "web development",
  ],
  react: [
    "react",
    "next.js",
    "nextjs",
    "hooks",
    "jsx",
    "frontend",
    "component",
  ],
  "data-science": [
    "data",
    "python",
    "pandas",
    "machine learning",
    "ml",
    "ai",
    "analytics",
    "statistics",
  ],
  "ui-design": [
    "design",
    "ui",
    "ux",
    "figma",
    "interface",
    "typography",
    "visual",
    "prototype",
  ],
  copywriting: [
    "writing",
    "copy",
    "copywriting",
    "content",
    "marketing",
    "brand",
    "email",
  ],
  "product-management": [
    "product",
    "management",
    "pm",
    "roadmap",
    "discovery",
    "agile",
    "scrum",
  ],
  leadership: [
    "leadership",
    "management",
    "team",
    "manager",
    "executive",
    "strategy",
  ],
  "public-speaking": [
    "speaking",
    "presentation",
    "public",
    "communication",
    "storytelling",
  ],
};
