export const PLATFORM_SETTINGS_KEYS = {
  SITE_NAME: "SITE_NAME",
  PLATFORM_FEE_PERCENTAGE: "PLATFORM_FEE_PERCENTAGE",
  ALLOW_REGISTRATION: "ALLOW_REGISTRATION",
} as const;

export type PlatformSettingKey =
  (typeof PLATFORM_SETTINGS_KEYS)[keyof typeof PLATFORM_SETTINGS_KEYS];

export const PLATFORM_SETTINGS_DEFAULTS = {
  [PLATFORM_SETTINGS_KEYS.SITE_NAME]: "Skillora",
  [PLATFORM_SETTINGS_KEYS.PLATFORM_FEE_PERCENTAGE]: "15",
  [PLATFORM_SETTINGS_KEYS.ALLOW_REGISTRATION]: "true",
} as const;

export const DEFAULT_PLATFORM_FEE_PERCENTAGE = Number(
  PLATFORM_SETTINGS_DEFAULTS[PLATFORM_SETTINGS_KEYS.PLATFORM_FEE_PERCENTAGE],
);
